version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      REGION: eu-est-1
    depends_on:
      - db
    networks:
      - crud-service
  db:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - 8000:8000
    volumes:
      - db-data:/home/dynamodblocal/data
    networks:
      - crud-service
  db-provisioner:
    image: amazon/aws-cli
    entrypoint: >
      bash -c 'aws dynamodb create-table \
        --endpoint-url http://db:8000/ \
        --table-name Music \
        --table-class STANDARD \
        --attribute-definitions AttributeName=Id,AttributeType=S AttributeName=Data,AttributeType=S \
        --key-schema AttributeName=Id,KeyType=HASH AttributeName=Data,KeyType=RANGE \
        --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
        --region us-east-1 '
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      REGION: eu-est-1
    depends_on:
      - db
    networks:
      - crud-service

volumes:
  db-data:

networks:
  crud-service:
    