version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
      - .:/app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      AWS_ACCESS_KEY_ID: DUMMY
      AWS_SECRET_ACCESS_KEY: DUMMY
      AWS_DYNAMODB_ENDPOINT: http://db:8000
      AWS_REGION: us-est-1
    depends_on:
      - db
    networks:
      - crud-service
  db:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    volumes:
      - db-data:/home/dynamodblocal/data
    networks:
      - crud-service
  db-provisioner:
    image: amazon/aws-cli
    entrypoint: >
      bash -c 'aws dynamodb create-table \
        --table-name Invoice \
        --attribute-definitions \
          AttributeName=Id,AttributeType=S \
          AttributeName=CreatedAt,AttributeType=S \
        --key-schema \
          AttributeName=Id,KeyType=HASH \
          AttributeName=CreatedAt,KeyType=RANGE \
        --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
        --billing-mode=PROVISIONED \
        --table-class STANDARD \
        --endpoint-url http://db:8000/'
    environment:
      AWS_ACCESS_KEY_ID: DUMMY
      AWS_SECRET_ACCESS_KEY: DUMMY
      AWS_REGION: us-est-1
    depends_on:
      - db
    networks:
      - crud-service

volumes:
  db-data:


networks:
  crud-service:
